import "@testing-library/jest-dom/vitest";
import { cleanup, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { GroupBy, GroupedPortfolioRow, NormalizedPosition, RequestFailureViewModel } from "@/lib/portfolio/contracts";
import { GroupByControl, PortfolioEmptyState, PortfolioFilteredEmptyState, PortfolioLoadingSkeleton, PortfolioPartialWarning, PortfolioSearch, PortfolioSummary, PortfolioTable, PortfolioTotalError, ProvenanceBadge, WalletSummary } from "./index";

afterEach(cleanup);
const position: Readonly<NormalizedPosition> = { positionKind: "wallet-token", walletId: "primary", walletLabel: "Primary", walletAddress: "0x1234567890abcdef1234567890abcdef12345678", networkId: "eip155:1", assetInstanceId: "eip155:1/native", canonicalAssetId: "asset:eth", name: "Ether", symbol: "ETH", contractAddress: null, decimals: 18, quantity: 2, priceUsd: 3000, valueUsd: 6000, source: { provider: "Mocked data", providerAssetId: "eth-mainnet", priceProvider: "Mocked prices", priceTimestamp: "2026-07-21T18:00:00.000Z" } };
const unpriced: Readonly<NormalizedPosition> = { ...position, assetInstanceId: "eip155:1/unknown", canonicalAssetId: "asset:unknown", name: "Mystery", symbol: "MYST", priceUsd: null, valueUsd: null, source: { provider: "Mocked data", priceProvider: null } };
const smallPosition: Readonly<NormalizedPosition> = { ...position, assetInstanceId: "eip155:1/small", canonicalAssetId: "asset:small", name: "Small Cap", symbol: "SMOL", quantity: 10, priceUsd: 50, valueUsd: 500 };
const failure: Readonly<RequestFailureViewModel> = { targetId: "primary-base", walletLabel: "Primary", networkLabel: "Base", message: "Provider timed out" };
function row(groupBy: GroupBy): Readonly<GroupedPortfolioRow> { return { id: `${groupBy}:eth`, groupBy, label: groupBy === "network" ? "Ethereum" : groupBy === "wallet" ? "Primary" : "Ether", symbol: groupBy === "token" ? "ETH" : undefined, quantity: groupBy === "token" ? 2 : null, valueUsd: 6000, portfolioPercent: 75.25, positionCount: 2, assetCount: 2, walletCount: 1, networkCount: 2, positions: [position, unpriced], hasUnpricedPositions: true }; }
const smallRow: Readonly<GroupedPortfolioRow> = { id: "token:small", groupBy: "token", label: "Small Cap", symbol: "SMOL", quantity: 10, valueUsd: 500, portfolioPercent: 6.25, positionCount: 1, assetCount: 1, walletCount: 1, networkCount: 1, positions: [smallPosition], hasUnpricedPositions: false };

describe("portfolio controls", () => {
  it("calls search and grouping callbacks", async () => { const user = userEvent.setup(); const search = vi.fn(); const group = vi.fn(); render(<><PortfolioSearch value="" onChange={search} resultCount={3} /><GroupByControl value="token" onChange={group} /></>); await user.type(screen.getByRole("searchbox", { name: "Search portfolio" }), "e"); await user.click(screen.getByRole("button", { name: "Network" })); expect(search).toHaveBeenCalledWith("e"); expect(group).toHaveBeenCalledWith("network"); expect(screen.getByText("3 results")).toHaveAttribute("aria-live", "polite"); expect(screen.getByRole("button", { name: "Token" })).toHaveAttribute("aria-pressed", "true"); });
});

describe("portfolio content", () => {
  it("labels complete and partial totals", () => { const { rerender } = render(<PortfolioSummary summary={{ totalValueUsd: 6000, pricedPositionCount: 1, unpricedPositionCount: 0, isIncomplete: false }} />); expect(screen.getByText("Complete total")).toBeInTheDocument(); rerender(<PortfolioSummary summary={{ totalValueUsd: 6000, pricedPositionCount: 1, unpricedPositionCount: 1, isIncomplete: true }} />); expect(screen.getByText("Partial total")).toBeInTheDocument(); expect(screen.getByText("1 unpriced position")).toBeInTheDocument(); expect(screen.getByText(/excludes unpriced assets/i)).toBeInTheDocument(); });
  it("shows wallet values, counts, and incomplete value labels", () => { render(<WalletSummary wallets={[{ id: "primary", label: "Primary", address: position.walletAddress, totalValueUsd: 6000, assetCount: 2, networkCount: 2, isIncomplete: true }]} />); expect(screen.getByTitle(position.walletAddress)).toHaveTextContent("0x1234…5678"); expect(screen.getByText("2 assets · 2 networks")).toBeInTheDocument(); expect(screen.getByText("Value incomplete")).toHaveAttribute("title", "Some assets are missing prices, so this wallet total excludes them."); });
  it("shows percentages, counts, unpriced assets, provenance, and grouped totals", () => { render(<PortfolioTable rows={[row("token")]} groupBy="token" />); const table = screen.getByRole("table", { name: "Portfolio holdings" }); expect(within(table).getAllByText("75.3%")).toHaveLength(2); expect(within(table).getByText("1 wallet · 2 networks")).toBeInTheDocument(); expect(within(table).getAllByText("2 positions")).toHaveLength(2); expect(within(table).getByText("Grouped total")).toBeInTheDocument(); expect(within(table).getByText("1 group shown")).toBeInTheDocument(); expect(within(table).getByText("Excludes unpriced")).toBeInTheDocument(); expect(within(table).getByLabelText("Data from Mocked data")).toBeInTheDocument(); });
  it("sorts grouped rows by value or portfolio percentage", async () => { const user = userEvent.setup(); render(<PortfolioTable rows={[smallRow, row("token")]} groupBy="token" />); const table = screen.getByRole("table", { name: "Portfolio holdings" }); expect(within(table).getByRole("columnheader", { name: /value/i })).toHaveAttribute("aria-sort", "descending"); expect(within(table).getAllByRole("row")[1]).toHaveTextContent("Ether"); await user.click(within(table).getByRole("button", { name: "Sort by value ascending" })); expect(within(table).getByRole("columnheader", { name: /value/i })).toHaveAttribute("aria-sort", "ascending"); expect(within(table).getAllByRole("row")[1]).toHaveTextContent("Small Cap"); await user.click(within(table).getByRole("button", { name: "Sort by portfolio descending" })); expect(within(table).getByRole("columnheader", { name: /portfolio/i })).toHaveAttribute("aria-sort", "descending"); expect(within(table).getAllByRole("row")[1]).toHaveTextContent("Ether"); });
  it("expands and collapses position composition accessibly", async () => { const user = userEvent.setup(); render(<PortfolioTable rows={[row("token")]} groupBy="token" />); const show = screen.getByRole("button", { name: "Show composition for Ether" }); expect(show).toHaveAttribute("aria-expanded", "false"); expect(screen.queryByText("Position composition")).not.toBeInTheDocument(); await user.click(show); const hide = screen.getByRole("button", { name: "Hide composition for Ether" }); expect(hide).toHaveAttribute("aria-expanded", "true"); expect(hide).toHaveAttribute("aria-controls"); expect(screen.getByText("Position composition")).toBeInTheDocument(); expect(screen.getAllByText("Primary")).toHaveLength(2); expect(screen.getByText("2 ETH")).toBeInTheDocument(); expect(screen.getByText("Mocked prices")).toHaveAttribute("title", "2026-07-21T18:00:00.000Z"); expect(screen.getAllByText("Unavailable")).toHaveLength(2); expect(screen.getByText("Unpriced")).toBeInTheDocument(); await user.click(hide); expect(screen.queryByText("Position composition")).not.toBeInTheDocument(); });
  it.each([["network", "Network", "2 assets · 1 wallet"], ["wallet", "Wallet", "2 assets · 2 networks"]] as const)("renders %s aggregate labels", (groupBy, heading, counts) => { render(<PortfolioTable rows={[row(groupBy)]} groupBy={groupBy} />); expect(screen.getByRole("columnheader", { name: heading })).toBeInTheDocument(); expect(screen.getByText(counts)).toBeInTheDocument(); expect(screen.getByLabelText("Not applicable")).toBeInTheDocument(); });
  it("includes optional provenance detail", () => { render(<ProvenanceBadge provider="Mocked data" providerAssetId="eth-mainnet" />); expect(screen.getByLabelText("Data from Mocked data, provider asset eth-mainnet")).toBeInTheDocument(); });
});

describe("portfolio states", () => {
  it("renders loading, true-empty, and filtered-empty states", async () => { const user = userEvent.setup(); const clear = vi.fn(); const { rerender } = render(<PortfolioLoadingSkeleton rowCount={3} />); expect(screen.getByLabelText("Loading portfolio")).toHaveAttribute("aria-busy", "true"); rerender(<PortfolioEmptyState />); expect(screen.getByRole("heading", { name: "No assets found" })).toBeInTheDocument(); expect(screen.queryByRole("button")).not.toBeInTheDocument(); rerender(<PortfolioFilteredEmptyState query="doge" onClear={clear} />); expect(screen.getByText("“doge”")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Clear search" })); expect(clear).toHaveBeenCalledOnce(); });
  it("labels partial failures and exposes retry", async () => { const user = userEvent.setup(); const retry = vi.fn(); render(<PortfolioPartialWarning failures={[failure]} onRetry={retry} />); expect(screen.getByText(/portfolio total is partial/i)).toBeInTheDocument(); expect(screen.getByText("Primary")).toBeInTheDocument(); expect(screen.getByText(/on Base/)).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Retry unavailable balances" })); expect(retry).toHaveBeenCalledOnce(); });
  it("renders total error and disables retry while running", async () => { const user = userEvent.setup(); const retry = vi.fn(); const { rerender } = render(<PortfolioTotalError failures={[failure]} onRetry={retry} />); expect(screen.getByRole("alert")).toHaveTextContent("Portfolio could not be loaded"); expect(screen.getByText(/Provider timed out/)).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Retry loading portfolio" })); expect(retry).toHaveBeenCalledOnce(); rerender(<PortfolioTotalError failures={[failure]} isRetrying onRetry={retry} />); expect(screen.getByRole("button", { name: "Retrying…" })).toBeDisabled(); });
});
